### PR TITLE
fixed invalid number of parameters in truncate() function call

### PR DESCRIPTION
**Pull request by blazk**
hi @dvalters,
* truncate() call was broken
* added some unit tests for editing, deleting, creating global attributes

### CODE REVIEW

**Comment by blazk** [comment]
@dvalters can you wait, some unit test fails for python 3, weird..

**Comment by dvalters** [comment]
@blazk will do - (yes that's strange..)

**Comment by blazk** [comment]
@dvalters is_var_dir() did not work correctly in python3 (because some changes in strings/utf8 I guess)

**Comment by blazk** [comment]
ok I'm done, all checks passed!

**Pull request merged**
